export const subcategoriesMap = {
  food: [
    "American Restaurant",
    "Brazilian Restaurant",
    "Chinese Restaurant",
    "Fast Food Restaurant",
  ],
  sport: [
    "Gym",
    "Fitness center",
    "Sports club",
    "Sports complex",
    "Stadium",
    "Swimming pool",
    "Ski resort",
    "Playground",
    "Golf course",
  ],
  services: [
    "Barber shop",
    "Beauty saloon",
    "Child care agency",
    "Hair care",
    "Hair saloon",
    "Veterinary care",
  ],
  entertaiment: [
    "Amusement center",
    "Amusement park",
    "Aquarium",
    "Bowling alley",
    "Casino",
    "Community center",
    "Convention center",
    "Cultural center",
    "Dog park",
    "Event venue",
    "Hiking area",
    "Historical landmark",
    "Marina",
    "Movie rental",
    "Movie theater",
    "National Park",
    "Night club",
    "Park",
    "Tourist attraction",
    "Zoo",
  ],
  "health and wellnes": [
    "Dental clinic",
    "Dentist",
    "Doctor",
    "Drugstore",
    "Hospital",
    "Medical lab",
    "Pharmacy",
    "Physiotherapist",
    "Spa",
  ],
  lodging: [
    "Bed and breakfast",
    "Campground",
    "Camping cabin",
    "Cottage",
    "Extended stay hotel",
    "Farmstay",
    "Guest home",
    "Hostel",
    "Hotel",
    "Lodging",
    "Motel",
    "Private guest room",
    "Resort hotel",
    "Rv park",
  ],
  shopping: [
    "Auto parts store",
    "Bicycle store",
    "Book store",
    "Cell phone store",
    "Clothing store",
    "Convenience store",
    "Department store",
    "Discount store",
    "Electronics store",
    "Gift shop",
    "Grocery shop",
    "Hardware store",
    "Home goods store",
    "Home improvement store",
    "Jewelry store",
    "Liquor store",
    "Market",
    "Pet store",
    "Shoe store",
    "Shopping mall",
    "Sporting goods store",
    "Store",
    "Supermarket",
    "Wholesaler",
  ],
  education: [
    "Library",
    "Preschool",
    "Primary school",
    "School",
    "Secondary school",
    "University",
  ],
};
